/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface JsMacroError {
  kind: number
  message: string
}
export interface JsFileSystemOptions {
  read: (...args: any[]) => any
  readLink: (...args: any[]) => any
  kind: (...args: any[]) => any
  includeNodeModules?: NapiSideEffectsVariants
}
export interface FileSystem {
  fs?: JsFileSystemOptions
  includeNodeModules?: NapiSideEffectsVariants
  conditions?: number
  moduleDirResolver?: (...args: any[]) => any
  mode: number
  entries?: number
  extensions?: Array<string>
  packageExports: boolean
  typescript?: boolean
}
export interface ResolveOptions {
  filename: string
  specifierType: string
  parent: string
  packageConditions?: Array<string>
}
export interface FilePathCreateInvalidation {
  filePath: string
}
export interface FileNameCreateInvalidation {
  fileName: string
  aboveFilePath: string
}
export interface GlobCreateInvalidation {
  glob: string
}
export interface ResolveResult {
  resolution: unknown
  invalidateOnFileChange: Array<string>
  invalidateOnFileCreate: Array<FilePathCreateInvalidation | FileNameCreateInvalidation | GlobCreateInvalidation>
  query?: string
  sideEffects: boolean
  error: unknown
  moduleType: number
}
export interface JsInvalidations {
  invalidateOnFileChange: Array<string>
  invalidateOnFileCreate: Array<FilePathCreateInvalidation | FileNameCreateInvalidation | GlobCreateInvalidation>
  invalidateOnStartup: boolean
}
export const enum Type {
  JS = 0,
  JSX = 1,
  TS = 2,
  TSX = 3
}
export declare function transform(ty: Type, filename: string, code: string, callMacro: (...args: any[]) => any): object
export interface TransformResult {
  code: string
  map: string
}
export class Resolver {
  constructor(projectRoot: string, options: FileSystem)
  resolve(options: ResolveOptions): ResolveResult
  resolveAsync(): object
  resolveAsync(options: ResolveOptions): object
  getInvalidations(path: string): JsInvalidations
  getInvalidations(path: string): JsInvalidations
}
