/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface JsMacroError {
  kind: number
  message: string
}
export const enum Type {
  JS = 0,
  JSX = 1,
  TS = 2,
  TSX = 3
}
export function transform(ty: Type, code: string, callMacro: (...args: any[]) => any): object
export interface TransformResult {
  code: string
  map: string
}
